### ISSUE TITLE
‎

### ISSUE THREAD

**Issue by eschan145** [Skandarella/people#2]

**Comment by Skandarella** [comment]
An interesting question. the mod is based on mobs redo from TenPlus1. You could ask him, if he could add an option to prevent friendly fire to his mod, or someting like fractions: https://notabug.org/tenplus1/mobs_redo

**Comment by eschan145** [comment]
Could you make a feature for the warriors so they could patrol a certain area?

**Comment by eschan145** [comment]
I issued a pull request that should remove friendly fire to all mobs.
