### ISSUE TITLE
miner trading not working?

### ISSUE THREAD

**Issue by eris667** [Skandarella/people#5]
I am having a weird issue with the miner....
I have tamed the miner (hemp from the DR)
I can Mobs Redo Lasso the miner which lists as miner apple tamed, people:medminer_set

I peaked at line 85 here:
https://github.com/Skandarella/people/blob/main/medminer.lua
I when I right click with gold lumps the miner does not trade (tried all of the default:xxxx_lump items I had

If I right click with most items it triggers stay/walk

no issues with any of the other villagers / traders.......

**Comment by eris667** [comment]
Are the drops and getitem name swapped ?
Line 5-10 vs Line 86, looks like it wants farming dishes to drop random lumps, but the docs say random lumps for farming dishes??

_Miner spawning at mineshaft, trades default lumps for farming dishes_
From: https://content.minetest.net/packages/Liil/people/

**Comment by Skandarella** [comment]
Seems to be a problem with the guide, I have corrected the instructions in the guide, I hope everything is right now.

**Comment by eris667** [comment]
Tested with apple pie, trades as expected -- I kept reading the docs, forum posts, minetestDb description and finally tried to understand the code to figure it out

Closed -- ty for all of your great mods
